// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TerraNova.Infrastructure.Persistence;

#nullable disable

namespace TerraNova.Infrastructure.Migrations
{
    [DbContext(typeof(TerraNovaContext))]
    [Migration("20260604045717_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TerraNova.Domain.Entities.AlertaAgricola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_alerta");

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_alerta");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("nivel_alerta");

                    b.Property<int>("Resolvido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("resolvido");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("talhao_id_talhao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("TalhaoId");

                    b.ToTable("alerta_agricola", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.DadoTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_dado");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_leitura");

                    b.Property<Guid>("ReqApiId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("req_api_id_api");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("talhao_id_talhao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ReqApiId");

                    b.HasIndex("TalhaoId");

                    b.ToTable("dado_temporal", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_localizacao");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(8,6)")
                        .HasColumnName("loc_latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("loc_longitude");

                    b.HasKey("Id");

                    b.ToTable("localizacao", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Produtor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_produtor");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("senha");

                    b.Property<string>("TelefoneContato")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("produtor", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Propriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_propriedade");

                    b.Property<Guid>("LocalizacaoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("localizacao_id_localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<Guid>("ProdutorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("produtor_id_produtor");

                    b.Property<decimal>("TamanhoTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("tamanho_total");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId")
                        .IsUnique();

                    b.HasIndex("ProdutorId");

                    b.ToTable("propriedade", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.ReqApi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_api");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_analise");

                    b.Property<Guid>("TipoApiId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("tipo_api_id_tipo");

                    b.Property<string>("TipoParam")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("tipo_param");

                    b.HasKey("Id");

                    b.HasIndex("TipoApiId");

                    b.ToTable("req_api", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Talhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_talhao");

                    b.Property<Guid>("LocalizacaoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("localizacao_id_localizacao");

                    b.Property<string>("NomeTalhao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_talhao");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("propriedade_id_propriedade");

                    b.Property<Guid>("TipoPlantacaoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("tipo_plantacao_id_tipo_plant");

                    b.Property<decimal>("VolumArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("volum_area");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId")
                        .IsUnique();

                    b.HasIndex("PropriedadeId");

                    b.HasIndex("TipoPlantacaoId");

                    b.ToTable("talhao", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_telefone");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NCHAR(2)")
                        .HasColumnName("ddd")
                        .IsFixedLength();

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("numero");

                    b.Property<Guid>("ProdutorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("produtor_id_produtor");

                    b.HasKey("Id");

                    b.HasIndex("ProdutorId")
                        .IsUnique();

                    b.ToTable("telefone", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.TipoApi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tipo");

                    b.Property<string>("NomeTipoApi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("tipo_api");

                    b.HasKey("Id");

                    b.ToTable("tipo_api", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.TipoPlantacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tipo_plant");

                    b.Property<string>("TipoPlant")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("tipo_plant");

                    b.HasKey("Id");

                    b.ToTable("tipo_plantacao", (string)null);
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.AlertaAgricola", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.Talhao", "Talhao")
                        .WithMany("Alertas")
                        .HasForeignKey("TalhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.DadoTemporal", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.ReqApi", "ReqApi")
                        .WithMany("DadosTemporais")
                        .HasForeignKey("ReqApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraNova.Domain.Entities.Talhao", "Talhao")
                        .WithMany("DadosTemporais")
                        .HasForeignKey("TalhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReqApi");

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Propriedade", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.Localizacao", "Localizacao")
                        .WithOne("Propriedade")
                        .HasForeignKey("TerraNova.Domain.Entities.Propriedade", "LocalizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerraNova.Domain.Entities.Produtor", "Produtor")
                        .WithMany("Propriedades")
                        .HasForeignKey("ProdutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.ReqApi", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.TipoApi", "TipoApi")
                        .WithMany("ReqApis")
                        .HasForeignKey("TipoApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoApi");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Talhao", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.Localizacao", "Localizacao")
                        .WithOne("Talhao")
                        .HasForeignKey("TerraNova.Domain.Entities.Talhao", "LocalizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TerraNova.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany("Talhoes")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraNova.Domain.Entities.TipoPlantacao", "TipoPlantacao")
                        .WithMany("Talhoes")
                        .HasForeignKey("TipoPlantacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Propriedade");

                    b.Navigation("TipoPlantacao");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("TerraNova.Domain.Entities.Produtor", "Produtor")
                        .WithOne("TelefoneDetalhado")
                        .HasForeignKey("TerraNova.Domain.Entities.Telefone", "ProdutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Localizacao", b =>
                {
                    b.Navigation("Propriedade");

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Produtor", b =>
                {
                    b.Navigation("Propriedades");

                    b.Navigation("TelefoneDetalhado");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Propriedade", b =>
                {
                    b.Navigation("Talhoes");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.ReqApi", b =>
                {
                    b.Navigation("DadosTemporais");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.Talhao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("DadosTemporais");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.TipoApi", b =>
                {
                    b.Navigation("ReqApis");
                });

            modelBuilder.Entity("TerraNova.Domain.Entities.TipoPlantacao", b =>
                {
                    b.Navigation("Talhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
