<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TerraNova.Application</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TerraNova.Domain\TerraNova.Domain.csproj" />
        <ProjectReference Include="..\TerraNova.Integration\TerraNova.Integration.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Services\Implementations\SatVegService.cs" />
      <Compile Remove="Services\Implementations\NasaPowerService.cs" />
    </ItemGroup>
</Project>
